.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PACKTORY" "2" "November 2018" "" ""
.
.SH "NAME"
\fBpacktory\fR \- Tool to package Ruby gems into system packages\.
.
.SH "INSTALL"
You may install Packtory using Debian, RPM, Homebrew, or Rubygems\.
.
.P
Via Rubygems:
.
.IP "" 4
.
.nf

gem install packtory
.
.fi
.
.IP "" 0
.
.P
Via Homebrew:
.
.IP "" 4
.
.nf

brew tap packtory/tap
brew install packtory
.
.fi
.
.IP "" 0

